preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  com.android.application:
    version: +
  com.android.library:
    version-ref: com.android.application
  org.jetbrains.kotlin.android:
    version: +

libraries:
  com.google.android.material:
    material:
      version: +
  androidx.constraintlayout:
    constraintlayout:
      version: +
  junit:
    junit:
      version: +
  androidx.appcompat:
    appcompat:
      version: +
  androidx.core:
    core:
      version: +
    core-ktx:
      version-ref: <this>::core
  androidx.test.ext:
    junit:
      version: +
  androidx.test.espresso:
    espresso-core:
      version: +